In [6]:
import pandas as pd 
import collections
from datetime import timedelta
from dateutil.relativedelta import relativedelta
import numpy as np

import math
from datetime import datetime 
from datetime import datetime, timedelta


from powernad.API.Campaign import *
from powernad.API.RelKwdStat import *

import time

from time import sleep
from urllib.error import HTTPError

import urllib.request
from datetime import datetime, timedelta
import json

from tqdm.notebook import tqdm

In [7]:
toda = datetime.now()
time_month = toda - relativedelta(months=1)
time_month = time_month.strftime('%Y-%m-%d')
time_month= str(time_month)


yesterday = toda - relativedelta(days=1)
yesterday = yesterday.strftime('%Y-%m-%d')
yesterday = str(yesterday)



today = str(datetime.now().date())

In [8]:
dt_index = pd.date_range(start=time_month, end = yesterday)

date = pd.DataFrame(data=dt_index, columns=['날짜'])

In [9]:
BASE_URL = 'https://api.naver.com'
API_KEY = '0100000000aedd7e21ca248851339717a8c09555ed20e1e5cede79edfd948be51224d67f62'
SECRET_KEY = 'AQAAAACu3X4hyiSIUTOXF6jAlVXt0G36rz8arbVtCcBmmpCK0Q=='
CUSTOMER_ID = '1326555'

In [10]:

rel = RelKwdStat(BASE_URL, API_KEY, SECRET_KEY, CUSTOMER_ID)

def search_keyword(searchword):
    kwdDataList = rel.get_rel_kwd_stat_list(siteId=None, biztpId=None, hintKeywords=searchword, event=None, month=None, showDetail='1')
    kwd_result = (kwdDataList[0].relKeyword, #키워드
                 kwdDataList[0].monthlyPcQcCnt, #월간 검색수 (PC)
                 kwdDataList[0].monthlyMobileQcCnt, # 월간 검색수 (Mobile)
                 kwdDataList[0].monthlyPcQcCnt+kwdDataList[0].monthlyMobileQcCnt) # 월간 total 
    return(kwd_result[3])

client_id = "VwYdRR6MqJZJLGEOGqYr" 
client_secret = "9XtlZIiC59"

dictionary_yester={}
dictionary_now={}

In [38]:
# lis = ['검색하고자 하는 키워드 입력']
lis = ['위워크']

In [39]:
error=[]
for i in tqdm(lis):  
    sleep(1)
    try:
        if type(search_keyword(i)) !=str : 
            searchword = i.replace(" ","")
            a = search_keyword(searchword)


            url = "https://openapi.naver.com/v1/datalab/search"
            body = "{\"startDate\":\""+time_month+"\",\"endDate\":\""+today+"\",\"timeUnit\":\"date\",\"keywordGroups\":[{\"groupName\":\""+i+"\",\"keywords\":[\""+i+"\"]}]}";
            requested = urllib.request.Request(url)
            requested.add_header("X-Naver-Client-Id", client_id)
            requested.add_header("X-Naver-Client-Secret", client_secret)
            requested.add_header("Content-Type", "application/json")
            response = urllib.request.urlopen(requested, data=body.encode("utf-8"))
            rescode = response.getcode()

            if(rescode==200):
                response_body = response.read()
                output_data = response_body.decode('utf-8')
            else:
                print('Error code:'+ rescode)
                pass

            result = json.loads(output_data)


            date = [a['period'] for a in result['results'][0]['data']]


            aa = pd.DataFrame({'date':date, 
                          i:[a['ratio'] for a in result['results'][0]['data']],
                          })

            # 일일 데이터 계산 


            sleep(0.5)
            total = aa[i].sum()


            aa[i] = aa[i].apply(lambda x :((x / total)*float(a)))

        else : 
            pass

    except (TypeError, IndexError,KeyError,ValueError):
        print(" 타입 or 인덱스 에러,Value 에러:",i)
        error.append(i)
        pass


    except HTTPError:
        print('http 에러:', i )
        error.append(i)
        pass

        #여기부터 새로코딩함 
    try: 
        if type(search_keyword(i)) !=str : 
            searchword = i.replace(" ","")
            a = search_keyword(searchword)        

            dt_index = pd.date_range(start=time_month, end= yesterday)
            dt_list = dt_index.strftime("%Y-%m-%d").tolist()

            date = pd.DataFrame(data=dt_list, columns=['날짜'])

            spred = pd.merge(date,aa,left_on='날짜',right_on='date',how='outer')
            spred.drop(['date'],inplace=True, axis=1)

            spred.replace(np.nan,0,inplace=True)


            a=[] 

            for j in range(len(spred)) : 
                a.append(today)


            spred['수집날짜'] = a

            spred = spred[['날짜','수집날짜',i]]

            if i in dictionary_yester:

                pass

            else : 
                dictionary_yester[i]=[]



            dictionary_now[i]=spred

        else:
            pass

    except (TypeError, IndexError,KeyError,ValueError):

        pass

    sleep(0.5)
    try :
        if type(search_keyword(i)) !=str : 
            searchword = i.replace(" ","")
            a = search_keyword(searchword)        

            if dictionary_yester[i]==[]:
                dictionary_yester[i] = dictionary_now[i]
               # for k in range(3):
                #    sleep(1)
                 #   gc2.append_row(dictionary_now[i].iloc[-1-k,:].values.tolist()+[i])


            else : 
                pass 
        else:
            pass


    except (TypeError, IndexError,KeyError):
          pass


    except ValueError:


            yester_df= dictionary_yester[i]
            today_df = dictionary_now[i]


            yester_df.set_index('날짜',inplace=True)

            today_df.set_index('날짜',inplace=True)

            yester_df.update(today_df)


            tmpt = today_df.iloc[-1,:]

            yester_df = yester_df.append(tmpt)

            yester_df.reset_index(inplace=True)
            today_df.reset_index(inplace=True)

            #dictionary_yester[i] = yester_df

        ## 구글 API로 데이터 올리기
            # 2주간의 데이터만 구글 스프레드 시트에 올리겠다.

          #  for k in range(3):
           #     sleep(1)
            #    gc2.append_row(yester_df.iloc[-1-k,:].values.tolist()+[i])




            dictionary_yester[i] = yester_df


    except :
        print('API 에러',i)
        error.append(i)



    sleep(3)

  0%|          | 0/1 [00:00<?, ?it/s]

In [40]:
# dictionary_now['lis에서 정의했던 키워드 입력']
dictionary_now['위워크']

            날짜        수집날짜         위워크
0   2023-01-08  2023-02-08  242.581658
1   2023-01-09  2023-02-08  520.837069
2   2023-01-10  2023-02-08  485.163315
3   2023-01-11  2023-02-08  554.472361
4   2023-01-12  2023-02-08  521.856300
5   2023-01-13  2023-02-08  448.470275
6   2023-01-14  2023-02-08  278.255411
7   2023-01-15  2023-02-08  319.025431
8   2023-01-16  2023-02-08  427.065979
9   2023-01-17  2023-02-08  456.624290
10  2023-01-18  2023-02-08  445.412527
11  2023-01-19  2023-02-08  459.682039
12  2023-01-20  2023-02-08  374.064964
13  2023-01-21  2023-02-08  190.599874
14  2023-01-22  2023-02-08  176.330361
15  2023-01-23  2023-02-08  183.465090
16  2023-01-24  2023-02-08  233.408356
17  2023-01-25  2023-02-08  436.239280
18  2023-01-26  2023-02-08  441.335491
19  2023-01-27  2023-02-08  418.912019
20  2023-01-28  2023-02-08  276.216894
21  2023-01-29  2023-02-08  231.369894
22  2023-01-30  2023-02-08  458.662753
23  2023-01-31  2023-02-08  484.144029
24  2023-02-01  2023-02-08  454.585773
25  2023-02-02  2023-02-08  530.010315
26  2023-02-03  2023-02-08  429.104496
27  2023-02-04  2023-02-08  233.408356
28  2023-02-05  2023-02-08  260.928150
29  2023-02-06  2023-02-08  458.662753
30  2023-02-07  2023-02-08  429.104496

In [27]:
spark = dictionary_now['스파크플러스']

In [37]:
spark_sum = spark['스파크플러스'].tail(7).sum()

In [41]:
we = dictionary_now['위워크']

In [42]:
we_sum = we['위워크'].tail(7).sum()

In [43]:
spark_sum

2977.4417780855233

In [44]:
we_sum

2795.804339439078